server:
  port: 10000



spring:
  application:
    name: blog-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-auth-service
          uri: lb://blog-user-auth-service
          predicates:
            - Path=/api/auth/**, /api/user-auth-service/v3/api-docs
          filters:
            - StripPrefix=2
        - id: content-service
          uri: lb://blog-content-service
          predicates:
            - Path=/api/content/**, /api/content-service/v3/api-docs
          filters:
            - StripPrefix=2
        - id: file-media-service
          uri: lb://blog-file-media-service
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1
        - id: notification-messaging-service
          uri: lb://blog-notification-messaging-service
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
        - id: statistics-analytics-service
          uri: lb://blog-statistics-analytics-service
          predicates:
            - Path=/analytics/**
          filters:
            - StripPrefix=1
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - blog-gateway-service
      service-config:
        blog-user-auth-service:
          order: 1
          group-name: 用户服务

        blog-content-service:
          order: 2
          group-name: 内容服务

jwt:
  secret-key: fjeiowh833f3c292s
  access-token-expiration: 900000
  refresh-token-expiration: 9000000  
  refresh-threshold: 300000